
services:
  python-service:
    build: ./python-service
    ports:
      - "5050:5050"
    networks:
      - backend
  
  go-service:
    build: ./go-service
    networks:
      - backend
    depends_on:
      - python-service

  cpp-service:
    build: ./cpp-service
    networks:
      - backend

networks:
  backend:
    driver: bridge